
## Steps
- initialize V(s) to 0 for all states
- Iteratively apply the Bellman equation until convergence:
- image.png
- where P(s'|s, a) is the transition probability (equal for all moves)
- Use gamma = 1 (no discounting)
- Stop when maximum change in V(s) across all states is < 1e - 4.

## Psuedo Code
- set grid size (NxN) - done
- Define rewards for each state (-1 per move, 0 for terminal state) - done
- initialize value function V(s) = 0 for each states - done
- set discount factor (gamma) = 1 and convergence threshold (theta) 
- Define possible actions: up, down, left, right.
- Repeat until value converges:
- track maximum changes in values
- create a copy of current value function V_new
- for each state s (excluding the terminal state):
- compute new value using the Bellman Equation:
- for each action, calculate:
- next state s' (handling grid boundaries)
- expected value update: sum over all possible s'
- update V_new(s)
- track max change (to see if converged)
- Set V = V_new (update value function)
- if threshold reached, then stop
- Print the final value function. It would look something like this:
[[-59.42367735 -57.42387125 -54.2813141  -51.71012579]
 [-57.42387125 -54.56699476 -49.71029394 -45.13926711]
 [-54.2813141  -49.71029394 -40.85391609 -29.99766609]
 [-51.71012579 -45.13926711 -29.99766609   0.        ]]
 

In [8]:
import numpy as np

# Grid parameters
n = 4  # 4x4 grid
gamma = 1.0  # No discounting
theta = 1e-4  # Convergence threshold

# Initialize value function to zeros
V = np.zeros((n, n))

# Initialize rewards (-1 everywhere except terminal state)
rewards = np.full((n, n), -1)
rewards[n-1, n-1] = 0  # Terminal state has 0 reward

# Define possible actions (up, down, left, right)
actions = [(-1, 0), (1, 0), (0, -1), (0, 1)]

# Value iteration
iteration = 0
while True:
    delta = 0  # Track maximum change
    
    # Create a copy of current value function
    V_new = V.copy()
    
    # Iterate through all states
    for i in range(n):
        for j in range(n):
            # Skip the terminal state (bottom-right corner)
            if i == n-1 and j == n-1:
                continue
            
            # Current state value
            old_value = V[i, j]
            
            # Initialize the expected value calculation
            expected_values = []
            
            # For each action, calculate expected value
            for action in actions:
                # Find next state
                next_i = i + action[0]
                next_j = j + action[1]
                
                # Check if next state is valid (within grid boundaries)
                if 0 <= next_i < n and 0 <= next_j < n:
                    # Valid move - calculate expected value
                    expected_value = rewards[i, j] + gamma * V[next_i, next_j]
                    expected_values.append(expected_value)
                else:
                    # Invalid move (out of bounds) - agent stays in the same place
                    expected_value = rewards[i, j] + gamma * V[i, j]
                    expected_values.append(expected_value)
            
            # Update value with the average (since all actions have equal probability 0.25)
            V_new[i, j] = sum(expected_values) / len(actions)
            
            # Track maximum change for convergence check
            delta = max(delta, abs(old_value - V_new[i, j]))
    
    # Update value function
    V = V_new
    
    iteration += 1
    print(f"Iteration {iteration}, Max Change: {delta}")
    
    # Check for convergence
    if delta < theta:
        break

print("\nFinal Value Function:")
print(V)


Iteration 1, Max Change: 1.0
Iteration 2, Max Change: 1.0
Iteration 3, Max Change: 1.0
Iteration 4, Max Change: 1.0
Iteration 5, Max Change: 1.0
Iteration 6, Max Change: 1.0
Iteration 7, Max Change: 0.9951171875
Iteration 8, Max Change: 0.989013671875
Iteration 9, Max Change: 0.9793701171875
Iteration 10, Max Change: 0.9686279296875
Iteration 11, Max Change: 0.9558029174804688
Iteration 12, Max Change: 0.9422607421875
Iteration 13, Max Change: 0.9276008605957031
Iteration 14, Max Change: 0.9125607013702393
Iteration 15, Max Change: 0.8969874978065491
Iteration 16, Max Change: 0.881277322769165
Iteration 17, Max Change: 0.8653794005513191
Iteration 18, Max Change: 0.8495067656040192
Iteration 19, Max Change: 0.8336478527635336
Iteration 20, Max Change: 0.8179172677919269
Iteration 21, Max Change: 0.8023163387551904
Iteration 22, Max Change: 0.7869063090038253
Iteration 23, Max Change: 0.7716910272938549
Iteration 24, Max Change: 0.7567025230819127
Iteration 25, Max Change: 0.74194358939

## Non working code

In [2]:
import numpy as np
n = 4
value = np.zeros((n, n), dtype=int)
print(value)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
- Value is 0 in the 0,0

In [16]:
# value[row,col]
row = 0
col = 0
gamma = 1

# actions 
right = value[row,col+1]
down = value[row+1,col]
up = value[row-1,col]
left = value[row,col-1]



# bellman_eqn = reward[row, col] + gamma * value[row, col]



In [27]:
value[0,0]

np.int64(0)

In [23]:
left

np.int64(0)

In [7]:
# explore all paths

n = 4
value_matrix = np.zeros((n, n), dtype=int)
reward_matrix = np.full((4, 4), -1)

# Set the last element (4, 4) to 0
reward_matrix[3, 3] = 0
max_convergence = 0

gamma = 1




def recursion(index, max_convergence, v_new=0):

    row, col = index

    right =  row,col+1
    down =  row+1,col
    up =  row-1,col
    left = row,col-1

    path_dict = {
        'right': right,
        'down' : down,
        'up' : up,
        'left' : left
        }

    # paths = [left, right, up, down]
    value_dict = {}


    for path_name, path_value in path_dict.items():
        # if max_convergence < 1e-4:
        #     return max_convergence
        if min(path_value) > 0 and max(path_value)<4:
            if path_value == (3,3):
                reward = 0
            else:
                reward = -1
            
                    
            # calculate bellman
            v_new = v_new + (reward + gamma * value_matrix[path_value])
            print(f'Exploring {path_name} for {index} -> {path_value}: new_Val : {v_new}')
            max_convergence = max_convergence + (value_matrix[path_value] - v_new)
            value_dict[path_name] = value_matrix[path_value] - v_new

            # value_matrix[path_name] = v_new
            value_final = value_matrix[path_value] + recursion(path_value, max_convergence)
            return value_final
            
        else:
            continue



for index, value in np.ndenumerate(value_matrix):
    max_convergence = 0
    print(recursion(index, max_convergence))


None
Exploring down for (0, 1) -> (1, 1): new_Val : -1
Exploring right for (1, 1) -> (1, 2): new_Val : -1
Exploring right for (1, 2) -> (1, 3): new_Val : -1
Exploring down for (1, 3) -> (2, 3): new_Val : -1
Exploring down for (2, 3) -> (3, 3): new_Val : 0
Exploring up for (3, 3) -> (2, 3): new_Val : -1
Exploring down for (2, 3) -> (3, 3): new_Val : 0
Exploring up for (3, 3) -> (2, 3): new_Val : -1
Exploring down for (2, 3) -> (3, 3): new_Val : 0
Exploring up for (3, 3) -> (2, 3): new_Val : -1
Exploring down for (2, 3) -> (3, 3): new_Val : 0
Exploring up for (3, 3) -> (2, 3): new_Val : -1
Exploring down for (2, 3) -> (3, 3): new_Val : 0
Exploring up for (3, 3) -> (2, 3): new_Val : -1
Exploring down for (2, 3) -> (3, 3): new_Val : 0
Exploring up for (3, 3) -> (2, 3): new_Val : -1
Exploring down for (2, 3) -> (3, 3): new_Val : 0
Exploring up for (3, 3) -> (2, 3): new_Val : -1
Exploring down for (2, 3) -> (3, 3): new_Val : 0
Exploring up for (3, 3) -> (2, 3): new_Val : -1
Exploring down fo

RecursionError: maximum recursion depth exceeded while calling a Python object

In [42]:
value_matrix

array([[ 0,  0,  0,  0],
       [ 0, -4, -4, -3],
       [ 0, -4, -4, -3],
       [ 0, -3, -3,  0]])

In [39]:
print(max_convergence)

28


In [35]:
min([0,-1]) < 0

True

In [29]:
import numpy as np

matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

for index, value in np.ndenumerate(matrix):
    # print(f"Element at {index}: {value}")

Element at (0, 0): 1
Element at (0, 1): 2
Element at (0, 2): 3
Element at (0, 3): 4
Element at (1, 0): 5
Element at (1, 1): 6
Element at (1, 2): 7
Element at (1, 3): 8
Element at (2, 0): 9
Element at (2, 1): 10
Element at (2, 2): 11
Element at (2, 3): 12
Element at (3, 0): 13
Element at (3, 1): 14
Element at (3, 2): 15
Element at (3, 3): 16


In [22]:
bellman_eqn

np.int64(-1)

In [3]:
reward = np.full((4, 4), -1)

# Set the last element (4, 4) to 0
reward[3, 3] = 0

print(reward)

[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1  0]]


- on a current state check what are the possible options avl
- Then loop through all the options
- calculate the bellman eqn for all the options (v_new) = reward + gamma * v_next

In [46]:
print('val', value_matrix)
print('reward', reward_matrix)

val [[ 0  0  0  0]
 [ 0 -4 -4 -3]
 [ 0 -4 -4 -3]
 [ 0 -3 -3  0]]
reward [[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1  0]]


In [6]:
discounting = 0
1e-4 

0.0001

In [ ]:
reward

In [ ]:
# apply bellman's equation

value = reward + gamma*

In [ ]:
# Actions

left = 
- right
- up
- down

In [60]:
import numpy as np

# Grid parameters
n = 4  # 4x4 grid
gamma = 1.0  # No discounting
theta = 1e-4  # Convergence threshold

# Initialize value function to zeros
V = np.zeros((n, n))

# Initialize rewards (-1 everywhere except terminal state)
rewards = np.full((n, n), -1)
rewards[n-1, n-1] = 0  # Terminal state has 0 reward

# Define possible actions (up, down, left, right)
actions = [(-1, 0), (1, 0), (0, -1), (0, 1)]

# Value iteration
iteration = 0
while True:
    delta = 0  # Track maximum change
    
    # Create a copy of current value function
    V_new = V.copy()
    
    # Iterate through all states
    for i in range(n):
        for j in range(n):
            # Skip the terminal state (bottom-right corner)
            if i == n-1 and j == n-1:
                continue
            
            # Current state value
            old_value = V[i, j]
            
            # Initialize the expected value calculation
            expected_values = []
            
            # For each action, calculate expected value
            for action in actions:
                # Find next state
                next_i = i + action[0]
                next_j = j + action[1]
                
                # Check if next state is valid (within grid boundaries)
                if 0 <= next_i < n and 0 <= next_j < n:
                    # Valid move - calculate expected value
                    expected_value = rewards[i, j] + gamma * V[next_i, next_j]
                    expected_values.append(expected_value)
                else:
                    # Invalid move (out of bounds) - agent stays in the same place
                    expected_value = rewards[i, j] + gamma * V[i, j]
                    expected_values.append(expected_value)
            
            # Update value with the average (since all actions have equal probability 0.25)
            V_new[i, j] = sum(expected_values) / len(actions)
            
            # Track maximum change for convergence check
            delta = max(delta, abs(old_value - V_new[i, j]))
    
    # Update value function
    V = V_new
    
    iteration += 1
    print(f"Iteration {iteration}, Max Change: {delta}")
    
    # Check for convergence
    if delta < theta:
        break

print("\nFinal Value Function:")
print(V)

Iteration 1, Max Change: 1.0
Iteration 2, Max Change: 1.0
Iteration 3, Max Change: 1.0
Iteration 4, Max Change: 1.0
Iteration 5, Max Change: 1.0
Iteration 6, Max Change: 1.0
Iteration 7, Max Change: 0.9951171875
Iteration 8, Max Change: 0.989013671875
Iteration 9, Max Change: 0.9793701171875
Iteration 10, Max Change: 0.9686279296875
Iteration 11, Max Change: 0.9558029174804688
Iteration 12, Max Change: 0.9422607421875
Iteration 13, Max Change: 0.9276008605957031
Iteration 14, Max Change: 0.9125607013702393
Iteration 15, Max Change: 0.8969874978065491
Iteration 16, Max Change: 0.881277322769165
Iteration 17, Max Change: 0.8653794005513191
Iteration 18, Max Change: 0.8495067656040192
Iteration 19, Max Change: 0.8336478527635336
Iteration 20, Max Change: 0.8179172677919269
Iteration 21, Max Change: 0.8023163387551904
Iteration 22, Max Change: 0.7869063090038253
Iteration 23, Max Change: 0.7716910272938549
Iteration 24, Max Change: 0.7567025230819127
Iteration 25, Max Change: 0.74194358939